### ISSUE TITLE
I don't believe the binary search implementation is correct

### ISSUE THREAD

**Issue by jimhester** [PRL-PRG/UFOs#26]
At https://github.com/PRL-PRG/UFOs/blob/84c8ac6476afdb5ee7993ab54dc6727e1e22377b/ufos/src/mappedMemory/sparseList.c#L92-L93

The key insight in the linked post seems to be that the sum needs to be done with _unsigned_ arithmetic, otherwise the sum overflows. Your implementation uses signed 64 bit integers in the sum, so I believe it would still have the same issue.

In languages with `>>>`, the sign is discarded, so the overflow doesn't matter, but C and C++ don't have this operator so you need to cast the operands to `uint64_t` before summing I believe.

See http://codepad.org/HnaW00QX for an example

**Comment by electroCutie** [comment]
@jimhester i think that setting the middle, low, and high markers to always be unsigned would also be correct, yes?

**Comment by jimhester** [comment]
yeah that should work as well

**Comment by electroCutie** [comment]
Put the fix into the latest patch on the feature branch for subsetting along with another fix

Thanks for the catch
